default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: to_do_list_v2_development
  username: postgres
  password: '01213022'
  host: 127.0.0.1
  port: 5432

test:
  <<: *default
  database: to_do_list_v2_test
  username: postgres
  password: '01213022'
  host: 127.0.0.1
  port: 5432

production:
  <<: *default
  database: <%= ENV["PGDATABASE"] %>
  username: <%= ENV["PGUSER"] %>
  password: <%= ENV["PGPASSWORD"] %>
  host: <%= ENV["PGHOST"] %>
  port: <%= ENV["PGPORT"] %>
